### ISSUE TITLE
Error: Cannot find module '@babel/runtime/regenerator'

### ISSUE THREAD

**Issue by codati** [DevelopingMagic/pdfassembler#12]
hi (:

npm init
npm i pdfassembler

create file index.js
```javascript
const PDFAssembler = require('pdfassembler').PDFAssembler;
```

node index.js
I have error 
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '@babel/runtime/regenerator'
Require stack:
- xxx/node_modules/pdfjs-dist/lib/core/pdf_manager.js
- xxx/node_modules/pdfassembler/dist/pdfassembler.js
- xxx/node_modules/pdfassembler/dist/index.js
- xxx/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (xxx/node_modules/pdfjs-dist/lib/core/pdf_manager.js:29:43)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'xxx/node_modules/pdfjs-dist/lib/core/pdf_manager.js',
    'xxx/node_modules/pdfassembler/dist/pdfassembler.js',
    'xxx/node_modules/pdfassembler/dist/index.js',
    'xxx/index.js'
  ]
}
```
npm -v
6.13.4
node -v
v12.14.1

**Comment by patroclos** [comment]
I'm having the same problem

**Comment by RyanPWalker** [comment]
Try installing `@babel/runtime` as a dependency?

**Comment by dragonman225** [comment]
I install `@babel/runtime` manually. By the way, I also have to install `core-js` and `web-streams-polyfill` manually before I can start using this library.
