### ISSUE TITLE
Doesn't work in the one place it's supposed to work, Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by shessafridi** [DevelopingMagic/pdfassembler#18]
Uncaught ReferenceError: process is not defined
    at node_modules/promise-queue/index.js (index.js:1:18)
    at __require2 (chunk-7FP5O474.js?v=ed278ede:10:50)
    at node_modules/pdfassembler/dist/pdfassembler.js (pdfassembler.js:1:306)
    at __require2 (chunk-7FP5O474.js?v=ed278ede:10:50)
    at node_modules/pdfassembler/dist/index.js (index.ts:1:1)
    at __require2 (chunk-7FP5O474.js?v=ed278ede:10:50)
    at index.ts:1:10
    
    
    this is a fresh install in a vite react js project

**Comment by Flinner** [comment]
See: https://stackoverflow.com/questions/41359504/webpack-bundle-js-uncaught-referenceerror-process-is-not-defined

I know this is an old issue, for future users:
not sure why or how this works

I've added:
```js
  plugins: [
     ....
    new webpack.ProvidePlugin({
      process: "process/browser",
    }),
  ],

```

and

```bash
yarn add process
```


regards
